# Site settings
name: Arun Setty
title: Arun Setty | Fullstack Developer, Product Architect
description: Building Broken
url: https://arunsetty.github.io/
baseurl: ''
email: arunsetty1729@gmail.com
cover: https://arunsetty.github.io/img/og.png
logo: https://arunsetty.github.io/img/emojis/technologist.png
resume: https://arunsetty.github.io/resume.pdf
social:
  - title: email
    url: mailto:arunsetty1729@gmail.com
  - title: twitter
    url: https://twitter.com/a_s_k_af
  - title: instagram
    url: https://instagram.com/a_s_k_af
  - title: github
    url: https://github.com/arunsetty
  - title: linkedin
    url: https://www.linkedin.com/in/arun-setty-kodavali/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
