# Site settings
name: Carston Hernke
title: Carston Hernke | Data
description: A data engineer that loves geospatial data, cold brew coffee, and new learning new things.
url: https://carston.org/
baseurl: ''
email: hernk009@umn.edu
cover: https://carston.org/img/og.png
logo: https://carston.org/img/emojis/male-technologist.png
resume: https://carston.org/resume.pdf

# Google services
google_analytics: UA-117124950-1

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
