# Site settings
name: Frederic Randall
title: Frederic Randall | Data Analyst
description: Data analyst with a passion for research and design.
url: https://AfredTX.github.io/
baseurl: ''
email: Fredrandall333@gmail.com
cover: https://AfredTX.github.io/img/og.png
logo: https://AfredTX.github.io/img/emojis/technologist.png
resume: https://github.com/AfredTX/AfredTX.github.io/blob/master/Frederic%20Randall%20Resume%202020(1).pdf
social:
  - title: email
    url: mailto:FredRandall333@gmail.com
  - title: twitter
    url: https://twitter.com/FredericRandal4
  - title: github
    url: https://github.com/AfredTX
  - title: linkedin
    url: https://www.linkedin.com/in/frandall-iii/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
