# Site settings
name: Carston Hernke
title: Carston Hernke | Data
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: http://carston.org
baseurl: ''
email: hernk009@umn.edu
logo: http://carston.org/img/emojis/male-technologist.png
resume: http://carston.org/resume.pdf

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
